services:

  playground:
    image: "playground:0.0.4"
    container_name: "playground_app"
    ports:
      - "8080:8080"
    networks:
      - playground_net
    depends_on:
      - redis
    environment:
        - REDIS_HOST=playground_redis

  redis:
    image: "redis:alpine"
    container_name: "playground_redis"
    ports:
      - "6380:6379"
    networks:
      - playground_net

networks:
  playground_net:
    driver: bridge
